name: CI
on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v3
      - name: "Fetch dependencies"
        run: |
          sudo apt install libgtest-dev libc++-17-dev clang-17 libcxxabi-17-dev
